version: '3.7'

services:
  api:
    image: ziralink.client
    build:
      context: ./
      dockerfile: ./src/ZiraLink.Client/Dockerfile
  sample-web-application:
    image: sample-web-application
    build:
      context: ./
      dockerfile: ./samples/SampleWebServer/Dockerfile      